java:
  build:
    maven: 
      command: "mvn -Dmaven.test.failure.ignore=true clean package" 
    gradle:
      command: "test"
  unittest:
    junit:
      command: "mvn test"
  codecoverage:
    jacoco:
      command: "mvn surefire-report:report-only"
  codequality:
    sonarqube:
      url: "https://sonarcloud.io"
      login: "44b2720c97020fd2e46525766221bf2ac48ffe73"
      organization: "ltipetclinic"
  
     
